name: Changelog tester

on:
  workflow_dispatch:
    inputs:
      branch_to_release:
        description: 'Publish release branch'
        required: true

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - name: checkout v2
        uses: actions/checkout@v2
      - name: Github Script
        uses: actions/github-script@v6
        with:
          script: |
            console.log("Hello world!")
      - name: Gitlog
        run: git log HEAD...${{ github.event.inputs.branch_type }}
