name: Changelog tester

on:
  workflow_dispatch:
    inputs:
      taggie:
        description: 'Publish release branch'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Git log
        run: |
          git log HEAD...${{ github.event.inputs.taggie }}
