name: Changelog tester

on:
  workflow_dispatch:
    inputs:
      taggie:
        description: 'Publish release branch'
        required: true

jobs:
  printlog:
    runs-on: ubuntu-latest
    steps:
      - run: git log
