name: Changelog tester

on:
  workflow_dispatch:
    inputs:
      taggie:
        description: 'Publish release branch'
        required: true

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      run: git log
