name: Changelog tester

on:
  workflow_dispatch:
    inputs:
      branch_to_release:
        description: 'Publish release branch'
        required: true

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        env:
          SHA: '${{env.parentSHA}}'
        with:
          script: |
            console.log("Hello world!")
